services:
  php-good:
    build:
      context: .
      dockerfile: ./good/Dockerfile
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${PSQLUSERPASS}
    volumes:
      - ./good/src:/var/www/html/ddss-good/src
      - ./good/public:/var/www/html/ddss-good/public
    depends_on:
      - postgresql
    ports:
      - 0:80
    networks:
      - mynetwork

  php-bad:
    build:
      context: .
      dockerfile: ./bad/Dockerfile
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${PSQLUSERPASS}
    volumes:
      - ./bad/src:/var/www/html/ddss-bad/src
      - ./bad/public:/var/www/html/ddss-bad/public
    depends_on:
      - postgresql
    ports:
      - 0:80
    networks:
      - mynetwork

  postgresql:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${PSQLPASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data: