services:
  php:
    # image: php:8.1.31-apache
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${PSQLUSERPASS}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgresql
    ports:
      - 0:80
    networks:
      - mynetwork

  postgresql:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${PSQLPASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data: